server:
  port: 5921

# 添加自定义配置
test:
  user: Taylor Swift

spring:
  # postgres数据库连接
  datasource:
    url: jdbc:postgresql://localhost:5432/db_wikidev?stringtype=unspecified
    username: scott
    password: tiger
    driver-class-name: org.postgresql.Driver
  # redis，选择第二个数据库
  redis:
    host: 127.0.0.1
    port: 6379
    password: redispwd
    database: 1
  servlet:
    # 上传文件的大小
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 配置mybatis所有Mapper.xml所在的路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# 打印所有的sql日志：sql，参数，结果
logging:
  level:
    org:
      abc:
        wiki:
          mapper: trace

# RocketMQ
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: default
