GET http://localhost:5921/ebook/list
Accept: application/json

###
GET http://localhost:5921/ebook/list?name=Oracle
Accept: application/json

###
GET http://localhost:5921/ebook/list?page=2&size=3
Accept: application/json

###
